### ISSUE TITLE
Too much space between icons in notification area, and different icon scaling.

### ISSUE THREAD

**Issue by GarikTester** [mateslackbuilds/msb#19]
### Slackware Version
14.2
### MATE Version
1.18 (latest)
### Description
Clean installation of Slackware 14.2, msb installed from binary packages. Space between icons is msb-specific bug 100%, but scaling bug is upstream (https://github.com/mate-desktop/mate-panel/issues/519)
![1](https://user-images.githubusercontent.com/25196267/27685466-f357cdac-5cd6-11e7-82f2-b7e010c44dc2.png)

**Comment by willysr** [comment]
may i know which theme is used?

**Comment by GarikTester** [comment]
arc-theme (20160605) from SBo, may be it's a little old).
Ark-Dark theme is selected.

**Comment by willysr** [comment]
Thanks for the information

since it's a third party theme outside MATE's provided theme and theming can be very tricky in GTK+3, can you try to update to the latest arc-theme first and see if it fixes your problem?

also, i would suggest to raise an issue to [mate-themes](https://github.com/mate-desktop/mate-themes/) since msb is just trying to package what upstream has provided. We don't make any changes downstream.

**Comment by GarikTester** [comment]
Thanks a lot! The problem was in old arc-theme version, which doesn't know about mate 1.18 transition to full GTK3.
